k8gb:
  dnsZones:
    - loadBalancedZone: "demo.k8gb-kubeconeu2023.com" # -- dnsZone controlled by gslb
      parentZone: "k8gb-kubeconeu2023.com" # -- main zone which would contain gslb zone to delegate
      dnsZoneNegTTL: 300 # -- Negative TTL for SOA record
  # -- host/ip[:port] format is supported here where port defaults to 53
  parentZoneDNSServers:
    # -- use these DNS server as a main resolver to enable cross k8gb DNS based communication
    - "1.1.1.1"
    - "8.8.8.8"
  # -- used for places where we need to distinguish between different Gslb instances
  clusterGeoTag: "francecentral"
  # -- comma-separated list of external gslb geo tags to pair with
  extGslbClustersGeoTags: "uksouth"
  # -- Reconcile time in seconds
  reconcileRequeueSeconds: 10

externaldns:
  interval: "10s"

azuredns:
  # -- Enable Azure DNS provider
  enabled: true
  createAuthSecret:
    enabled: true
    tenantId: myTenantID
    # -- subscription id which holds the Azure DNS zone
    subscriptionId: mySubscriptionID
    # -- Azure Resource Group which holds the Azure DNS Zone (which is defined as 'edgeDNSZone')
    resourceGroup: k8gb-kubeconeu2023
    aadClientId: myAADClientID
    aadClientSecret: myAADClientSecret
