name: Helm Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: dave-mcconnell/helm-gh-pages-microservices@master
        with:
          access-token: ${{ secrets.CR_TOKEN }}
          source-charts-folder: 'chart'
          destination-repo: ytsarev/ohmyglb
          destination-charts-folder: docs/helmrepo
