name: Helm Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: J12934/helm-gh-pages-action@master
        with:
          access-token: ${{ secrets.CR_TOKEN }}
          charts-folder: chart
