name: Terrascan

on:
  push:
    paths:
     - 'chart/k8gb/**'
  pull_request:
    branches:
      - master
    paths:
     - 'chart/k8gb/**'
permissions:
  contents: read

jobs:
  terrascan:
    runs-on: ubuntu-20.04
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: Checkout repository
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
    - name: Run Terrascan
      id: terrascan
      uses: accurics/terrascan-action@fad2372c88bb11afccc0b682bffbeffd443b56ed
      with:
        iac_type: helm
        iac_version: v3
        only_warn: false
        verbose: true
        sarif_upload: true
        iac_dir: chart/k8gb
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@fdcae64e1484d349b3366718cdfef3d404390e85
      with:
        sarif_file: terrascan.sarif
